# Generated by Django 3.2.4 on 2021-07-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20210705_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
