# Generated by Django 3.2.4 on 2021-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu_element', models.CharField(max_length=128, verbose_name='название элемента меню')),
            ],
        ),
    ]
